### ISSUE TITLE
MiGraphx installation failed

### ISSUE THREAD

**Issue by zhangjia3** [ROCm/AMDMIGraphX#1017]
rocm version: rocm-4.0.1
Compilation method:
git clone -b rocm-4.0.0 https://github.com.cnpmjs.org/ROCmSoftwarePlatform/AMDMIGraphX.git
cd AMDMIGraphX
mkdir build
CXX=/opt/rocm-4.0.1/llvm/bin/clang++ cmake ..
make -j 4

**The cmake process is as follow:**
root@a0dfd55e982c:/AMDMIGraphX/build# CXX=/opt/rocm-4.0.1/llvm/bin/clang++ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is Clang 12.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rocm-4.0.1/llvm/bin/clang++
-- Check for working CXX compiler: /opt/rocm-4.0.1/llvm/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found nlohmann_json: /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.8.0", minimum required is "3.8.0")
-- Performing Test HAS_HIP
-- Performing Test HAS_HIP - Success
-- Enable miopen backend
-- Clang tidy found: 12.0.0git
-- Clang tidy checks: boost-,bugprone-,cert-,clang-analyzer-,clang-diagnostic-,cppcoreguidelines-,google-,hicpp-multiway-paths-covered,hicpp-signed-bitwise,llvm-namespace-comment,misc-,modernize-,performance-,readability-,-clang-analyzer-alpha,clang-analyzer-alpha.core.CallAndMessageUnInitRefArg,clang-analyzer-alpha.core.Conversion,clang-analyzer-alpha.core.IdenticalExpr,clang-analyzer-alpha.core.PointerArithm,clang-analyzer-alpha.core.PointerSub,clang-analyzer-alpha.core.TestAfterDivZero,clang-analyzer-alpha.cplusplus.InvalidIterator,clang-analyzer-alpha.cplusplus.IteratorRange,clang-analyzer-alpha.cplusplus.MismatchedIterator,clang-analyzer-alpha.cplusplus.MisusedMovedObject,-clang-analyzer-optin.performance.Padding,-clang-diagnostic-deprecated-declarations,-clang-diagnostic-extern-c-compat,-clang-diagnostic-disabled-macro-expansion,-clang-diagnostic-unused-command-line-argument,-cppcoreguidelines-explicit-virtual-functions,-cppcoreguidelines-init-variables,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-bounds-constant-array-index,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-member-init,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-union-access,-cppcoreguidelines-pro-type-vararg,-cppcoreguidelines-special-member-functions,-google-readability-,-google-runtime-int,-google-runtime-references,-misc-macro-parentheses,-modernize-concat-nested-namespaces,-modernize-pass-by-value,-modernize-use-default-member-init,-modernize-use-nodiscard,-modernize-use-override,-modernize-use-trailing-return-type,-modernize-use-transparent-functors,-performance-type-promotion-in-math-fn,-readability-braces-around-statements,-readability-convert-member-functions-to-static,-readability-else-after-return,-readability-named-parameter,-readability-uppercase-literal-suffix,,--avoid-c-arrays,--explicit-constructor,--magic-numbers,--non-private-member-variables-in-classes,--use-auto,--use-emplace,--use-equals-default
-- Cppcheck not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0")
-- Found PythonInterp: /root/miniconda3/bin/python (found version "3.7.10")
-- Found PythonLibs: /root/miniconda3/lib/libpython3.7m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Failed
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Failed
-- Found pybind11: /root/miniconda3/include (found version "2.8.1" )
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- Build with rocblas
-- Performing Test HAS_HIP_LAMBDA_HOST_DEVICE
-- Performing Test HAS_HIP_LAMBDA_HOST_DEVICE - Failed
-- Could NOT find LATEX (missing: LATEX_COMPILER)
Latex builder not found. Latex builder is required only for building the PDF documentation for MIGraph and is not necessary for building the library, or any other components. To build PDF documentation run make in /AMDMIGraphX/doc/pdf, once a latex builder is installed.
-- Configuring done
-- Generating done
-- Build files have been written to: /AMDMIGraphX/build

**The error is as follows:**
AMDMIGraphX/src/msgpack.cpp:3:10: fatal error: 'msgpack.hpp' file not found
#include <msgpack.hpp>
^~~~~~~~~~~~~
1 error generated.
src/CMakeFiles/migraphx.dir/build.make:494: recipe for target 'src/CMakeFiles/migraphx.dir/msgpack.cpp.o' failed
make[2]: *** [src/CMakeFiles/migraphx.dir/msgpack.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:2848: recipe for target 'src/CMakeFiles/migraphx.dir/all' failed
make[1]: *** [src/CMakeFiles/migraphx.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
![11111](https://user-images.githubusercontent.com/42707056/144032311-0b412e4b-642f-49f8-8c6a-6308d8696fc0.JPG)

**Comment by pfultz2** [comment]
Did you install msgpack correctly?

**Comment by zhangjia3** [comment]
Hello, thank you for your reply. Could you tell me how to install msgpack correctly?
I'll verify that I installed it correctly



---Original---
From: "Paul Fultz ***@***.***&gt;
Date: Tue, Nov 30, 2021 22:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ROCmSoftwarePlatform/AMDMIGraphX] MiGraphx installation failed(Issue #1017)




 
Did you install msgpack correctly?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pfultz2** [comment]
You can build the dependencies and migraphx with rbuild:

```cpp
pip3 install https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz
rbuild build -d depend -B build --cxx=/opt/rocm/llvm/bin/clang++
```

This will build migraphx in the `build/` directory.

**Comment by zhangjia3** [comment]
I tried rbuild installation before, but the error is as follows：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ROCmSoftwarePlatform/AMDMIGraphX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 晚上11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ROCmSoftwarePlatform/AMDMIGraphX] MiGraphx installation failed (Issue #1017)





 
You can build the dependencies and migraphx with rbuild:
 pip3 install https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz rbuild build -d depend -B build --cxx=/opt/rocm/llvm/bin/clang++
 
This will build migraphx in the build/ directory.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangjia3** [comment]
@pfultz2 I tried rbuild installation before, but the error is as follows：
`cget -p depend ignore danmar/cppcheck
Ignore package danmar/cppcheck
cget -p depend ignore RadeonOpenCompute/clang-ocl
Ignore package RadeonOpenCompute/clang-ocl
cget -p depend ignore RadeonOpenCompute/rocm-cmake
Ignore package RadeonOpenCompute/rocm-cmake
cget -p depend ignore ROCm-Developer-Tools/HIP
Ignore package ROCm-Developer-Tools/HIP
cget -p depend ignore ROCmSoftwarePlatform/MIOpen
Ignore package ROCmSoftwarePlatform/MIOpen
cget -p depend ignore ROCmSoftwarePlatform/MIOpenGEMM
Ignore package ROCmSoftwarePlatform/MIOpenGEMM
cget -p depend ignore ROCmSoftwarePlatform/rocBLAS
Ignore package ROCmSoftwarePlatform/rocBLAS
cget -p depend install -f dev-requirements.txt
Downloading https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Download failed with error 400 for: //github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Failed to build package pfultz2/rocm-recipes
Traceback (most recent call last):
  File "/root/miniconda3/bin/rbuild", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/rbuild/cli.py", line 298, in w
    f(make_builder, *args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/rbuild/cli.py", line 332, in build
    b.prepare()
  File "/root/miniconda3/lib/python3.7/site-packages/rbuild/cli.py", line 269, in prepare
    cg('install', *tokens, cwd=self.get_source_dir())
  File "/root/miniconda3/lib/python3.7/site-packages/rbuild/cli.py", line 224, in cget
    self.cmd(['cget', '-p', self.get_prefix()] + list(args), **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/rbuild/cli.py", line 221, in cmd
    subprocess.check_call(c, **kwargs)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cget', '-p', 'depend', 'install', '-f', 'dev-requirements.txt']' returned non-zero exit status 1.`
Can I install this dependency library offline?
![22222](https://user-images.githubusercontent.com/42707056/144149805-18922a98-442a-4774-bf5f-773d91ef4ecd.JPG)

**Comment by zhangjia3** [comment]
@pfultz2 Hello, I checked the cause of this error and found that cget cannot download the required packages normally, but wget can download normally. Can you tell me to install these dependencies using cget offline as follows?
The error is as follows:
(base) root@ubuntu:/home/AMDMIGraphX# cget install https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Downloading https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz

Download failed with error 400 for: //github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Failed to build package https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
(base) root@ubuntu:/home/AMDMIGraphX# wget https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
--2021-12-01 11:50:51--  https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Connecting to 192.168.245.1:8088... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/ROCmSoftwarePlatform/rocm-recipes/archive/HEAD.tar.gz [following]
--2021-12-01 11:50:54--  https://github.com/ROCmSoftwarePlatform/rocm-recipes/archive/HEAD.tar.gz
Reusing existing connection to github.com:443.
Proxy request sent, awaiting response... 302 Found
Location: https://codeload.github.com/ROCmSoftwarePlatform/rocm-recipes/tar.gz/a9e6012a15035616f95a53d12cdb2f8862d35c00 [following]
--2021-12-01 11:50:55--  https://codeload.github.com/ROCmSoftwarePlatform/rocm-recipes/tar.gz/a9e6012a15035616f95a53d12cdb2f8862d35c00
Connecting to 192.168.245.1:8088... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'HEAD.tar.gz.1'

HEAD.tar.gz.1                                           [   <=>                                                                                                             ]   7.73K  13.6KB/s    in 0.6s

2021-12-01 11:50:59 (13.6 KB/s) - 'HEAD.tar.gz.1' saved [7918]
![Uploading 3333333.JPG…]()

**Comment by zhangjia3** [comment]
@pfultz2  Hello, I checked the cause of this error and found that cget cannot download the required packages normally, but wget can download normally. Can you tell me to install these dependencies using cget offline as follows?
The error is as follows:
(base) root@ubuntu:/home/AMDMIGraphX# cget install https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Downloading https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz

Download failed with error 400 for: //github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Failed to build package https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
(base) root@ubuntu:/home/AMDMIGraphX# wget https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
--2021-12-01 11:50:51-- https://github.com/pfultz2/rocm-recipes/archive/HEAD.tar.gz
Connecting to 192.168.245.1:8088... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/ROCmSoftwarePlatform/rocm-recipes/archive/HEAD.tar.gz [following]
--2021-12-01 11:50:54-- https://github.com/ROCmSoftwarePlatform/rocm-recipes/archive/HEAD.tar.gz
Reusing existing connection to github.com:443.
Proxy request sent, awaiting response... 302 Found
Location: https://codeload.github.com/ROCmSoftwarePlatform/rocm-recipes/tar.gz/a9e6012a15035616f95a53d12cdb2f8862d35c00 [following]
--2021-12-01 11:50:55-- https://codeload.github.com/ROCmSoftwarePlatform/rocm-recipes/tar.gz/a9e6012a15035616f95a53d12cdb2f8862d35c00
Connecting to 192.168.245.1:8088... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'HEAD.tar.gz.1'

HEAD.tar.gz.1 [ <=> ] 7.73K 13.6KB/s in 0.6s

2021-12-01 11:50:59 (13.6 KB/s) - 'HEAD.tar.gz.1' saved [7918]
![3333333](https://user-images.githubusercontent.com/42707056/144229874-10b73dba-36a8-44d5-af4a-ec585d9b64ed.JPG)

**Comment by scxiao** [comment]
Maybe you can try build a docker container as:

docker build -t mgx_container .

Then in the container, you can build migraphx

**Comment by causten** [comment]
Is this still an issue?
