### ISSUE TITLE
sub objects of a tuple argument are used as module return value

### ISSUE THREAD

**Issue by scxiao** [ROCm/AMDMIGraphX#1053]
The scenario is:
auto v = mod->add_instruction(make_op("topk"), data);
auto data = mod->add_instruction(make_op("get_tuple_elem", {{"index", 0}}), v);
auto ind = mod->add_instruction(make_op("get_tuple_elem", {{"index", 1}}), v);
mod->add_return({data, ind});

In this way, there is a bug that output param for ind will overwrite output param for data. The reason is, when doing lowering on the gpu, the alias of both the data and ind are for the output of the topk, then the second output param will overwrite the output param of the data.

**Comment by causten** [comment]
May have been fixed with #1183 .

**Comment by darren-amd** [comment]
Hi @scxiao,

This appears to be the same issue as in https://github.com/ROCm/AMDMIGraphX/issues/1090 which has been fixed here: https://github.com/ROCm/AMDMIGraphX/pull/1183. This is fixed in the latest version of ROCm, could you please update and let me know if the issue persists?

Thanks!
