### ISSUE TITLE
A question about Pytorch  inference

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#1206]
now I have an inference program using python API of pytorch,but it is very slow. I hope than it can be faster by using python API of migraphx,so I rewrite the program.But I do not know how to use gpu tensor directly instead of converting it to cpu tensor(like data.cpu().numpy()) which may have a side effect on performance.

**Comment by kahmed10** [comment]
This sounds similar to #1031. We are still making progress on this internally, but you may be able to find a workaround within pytorch to get the desired goal.

**Comment by qianqing13579** [comment]
@kahmed10 , there is a solution about this. for more details refer to #1031

**Comment by ppanchad-amd** [comment]
Hi @qianqing13579. Is this ticket still relevant? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
Hi @qianqing13579. Closing ticket due to lack of activity.  Please feel free to re-open ticket if you still encounter the issue with the latest ROCm. Thanks!
