### ISSUE TITLE
an error about migraphx::load

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#1330]
I use migraphx::save to save the CRNN((Convolutional Recurrent Neural Network)) model successfully,but migraphx::load can not load the saved model. I do not know why. The migraphx is from commit 7596f3f10ffc66b9c09d35bcc7b72af808f395af.

the model link : https://drive.google.com/file/d/18ftm_ve6vty7o5upiKbPGUuWL7wQ13ao/view?usp=sharing

the part of the code is as follows:
```
  // save
  migraphx::program net= migraphx::parse_onnx("dynamic_crnn_2048.onnx");
  migraphx::compile_options options;
  net.compile(migraphx::gpu::target{},options);
  migraphx::save(net, "CRNN.mxr");
  ...

   // load
    std::string pathOfModel="dynamic_crnn_2048.mxr";
    migraphx::program net = migraphx::load(pathOfModel);
    ...
```

**Comment by CharlieL7** [comment]
Are there any error outputs?

**Comment by qianqing13579** [comment]
@CharlieL7 ,Segmentation fault

**Comment by CharlieL7** [comment]
I'm not able to compile this model; same problem from the previous issue. It does look to be CPU memory maxing out. Need to make some adjustments on my system to test this out.

**Comment by qianqing13579** [comment]
@CharlieL7 ，this is the same model with issue #1319,I create a new issue .

**Comment by qianqing13579** [comment]
@CharlieL7 , you can use a smaller size to make the compile faster.the code:
```
    migraphx::onnx_options onnx_options;
    onnx_options.map_input_dims["input"]={1,1,32,256};
    migraphx::program net= migraphx::parse_onnx("dynamic_crnn_2048.onnx",onnx_options); 
```

**Comment by CharlieL7** [comment]
I have compiled the full model and I see the same segmentation fault on trying to load. There's likely an issue during the compiling process to begin with, as we shouldn't need to have 50+ GB of RAM to compile the model. I will need to investigate the issue. It might take me a while to pin down the cause. Let me know if you get any clarifying information.

**Comment by ppanchad-amd** [comment]
Hi @qianqing13579. Can you please check if your issue still exist with the latest ROCm? If not, please close the ticket. Thanks!

**Comment by darren-amd** [comment]
Hi @qianqing13579,

I tried compiling, saving, and loading the given model, and was able to do so successfully without any seg faults. Could you please try again on the latest version of ROCm/MIGraphX and see if the issue is resolved? I used the following python script:

```
import numpy as np
import migraphx as mgx
from functools import wraps

class Test():
    def __init__(self):
        print("Load model")
        self.model = Test.load_mgx_model()

    def load_mgx_model():
        file = "dynamic_crnn_2048"
        print("Parsing from onnx file...")
        model = mgx.parse_onnx(f"{file}.onnx")
        model.compile(mgx.get_target("gpu"))
        print("Saving model to mxr file...")
        mgx.save(model, f"{file}.mxr", format="msgpack")
        model = mgx.load(f"{file}.mxr", format="msgpack")
        print("Loaded Successfully")
        return model
    

if __name__ == "__main__":
    test = Test()
```
