### ISSUE TITLE
Unknown operator: SplitToSequence

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#1359]
I want to use fasterrcnn from https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth (pytorch torchvision model),but I get the error : Unknown operator: SplitToSequence

the onnx model link: https://drive.google.com/file/d/1vg7xY3JQ59yq-M-h6GM6zqqpk_Qh7Duj/view?usp=sharing

**Comment by TedThemistokleous** [comment]
Looks like I'll need to add that in. @qianqing13579. If you run the driver with migraphx from the build directory

`build/bin/driver onnx --list`    

You should get a list of supported operators currently in MIGraphX. It looks like we still need to add that functionality for SplitToSquence
