### ISSUE TITLE
paddle-ocr model fails to compile with fp16

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#1393]
paddle-ocr model fails to compile with fp16. the migraphx is from commit: 97a1ed2de7cd5103aed50b10c634adfe041e7681.
```
/opt/rocm/bin/migraphx-driver perf --fp16 ./PaddleOCR_rec.onnx
```
the output:
```
Compiling ... 
Reading: ./PaddleOCR_rec.onnx
terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /home/qianqing/MIGraphX/src/normalize_attributes.cpp:91: tune_attribute: TUNE_VECTOR: value out of range!
Aborted (core dumped)
```
the model link: https://drive.google.com/file/d/1SeuBp1oBcD_zFL_tsS4wxqCodI07juEs/view?usp=sharing

**Comment by causten** [comment]
Is this still an issue?

**Comment by ppanchad-amd** [comment]
Hi @qianqing13579. Closing ticket due to lack of activity. Please feel free to re-open the ticket if you still see the issue with the latest ROCm. Thanks!
