### ISSUE TITLE
an error about FasterRCNN

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#1472]
I'm running FastRCNN model from [link](https://drive.google.com/file/d/1oqbS2Wqv_F5c5y1A174lSkUgcSS1wbys/view?usp=sharing)
and the program is terminated without any output. the migrahx is from commit :https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/commit/97a1ed2de7cd5103aed50b10c634adfe041e7681

**Comment by causten** [comment]
@kahmed10  can you take a look.

**Comment by causten** [comment]
When I try to read the model I get...

migraphx-driver read ./faster_rcnn_r50_fpn_1x_coco.onnx
Reading: ./faster_rcnn_r50_fpn_1x_coco.onnx
Segmentation fault (core dumped)


I then tried to use Netron to view it and it can't understand the model either.

**Comment by nartmada** [comment]
Hi @qianqing13579, apologies for not following up.  Does this issue still exist with latest ROCm 6.0.2?  Thanks.

**Comment by ppanchad-amd** [comment]
Hi @qianqing13579. Closing ticket due to lack of activity. Please feel free to re-open ticket if you still see the issue with the latest ROCm. Thanks!
