### ISSUE TITLE
Performance regression issue

### ISSUE THREAD

**Issue by mxjecho** [ROCm/AMDMIGraphX#1484]
command:
migraphx-driver perf model.onnx

Issue:
I got different 'Rate' numbers when the same model is loaded with different weights. And the difference is not negligible.
For example, for Inception V3:
a) random initialization - Rate: 306.219/sec
b) load pre-trained weights- Rate: 284.733/sec
c) load all-0 weights: 319.312/sec

I'm curious as to why this is. Is this a normal phenomenon?

**Comment by CharlieL7** [comment]
The all zero weights being faster make sense. Unsure why the random initialization is faster. Can you supply the ONNX files used?

**Comment by nartmada** [comment]
Hi @mxjecho, apologies for the lack of response.  Do you still see this issue with latest ROCm 6.0.2?  Thanks.

**Comment by ppanchad-amd** [comment]
Hi @mxjecho. Closing ticket due to lack of activity.  Please feel free to re-open ticket if you still see the issue with the latest ROCm. Thanks!
