### ISSUE TITLE
Importing the Einsum operator is not supported

### ISSUE THREAD

**Issue by Yanxing-Shi** [ROCm/AMDMIGraphX#1551]
I was trying to test some handwritten models using AMDMIGraphX and the following error occurred when importing unet's onnx file:
`RuntimeError: code/AMDMIGraphX/src/onnx/onnx_parser.cpp:339: parse_graph: Unknown operator: Einsum`

Does AMDMIGraphX currently not support importing this operator `Einsum` ?

**Comment by CharlieL7** [comment]
MIGraphX does not support the `Einsum` operator at this time. Can I see how is the operator being used in the model? We might support a subset of the `Einsum` operator in the future. As it can map to a multitude of operators.

**Comment by CharlieL7** [comment]
It looks like the unet model is essentially using `Einsum` for inner products. The two notations I see are:

`b i d, b j d - > b i j` which is a transposed `Matmul`
`b i j, b j d -> b i d` which is normal `Matmul`

We could hard code a parser to find these strings, but it's probably better to make a parser that can handle these types of strings.
