### ISSUE TITLE
Torch MIGraphX 

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/AMDMIGraphX#1575]
Upstream the torch_migraphx codebase. Build necessary interfaces to use fx2mgx as a backend for torchdynamo in torch 2.0.

**Comment by causten** [comment]
Waiting on upstream support for inference graph (currently all training)
20/39 (SD total) operators mapped  SD end to end runs and just falls back to Torch operator solutions for the other 19
Need to add timer for running
Add MXR capabilities for migraphx perf report
Need to create the TorchMIGraphX wheel file
- Register, build, publish, wheel
