### ISSUE TITLE
Update .so versions scheme

### ISSUE THREAD

**Issue by umangyadav** [ROCm/AMDMIGraphX#1645]
Shared libraries versioning need to be like following : 
![MIGraphx version](https://user-images.githubusercontent.com/29876643/227660980-9a9d97ac-6d83-4ebe-83ef-b32397bad769.PNG)

**Comment by umangyadav** [comment]
Probably not necessary anymore. see this reply from paul freddy. 
If required, we can re-open this issue. 
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2267#issuecomment-1765397986

**Comment by umangyadav** [comment]
Related #2355

**Comment by pfultz2** [comment]
This hasn't been fixed yet.

**Comment by umangyadav** [comment]
Closing this one. If necessary open again later.
