### ISSUE TITLE
[RFC] Multi-target compilation in MIGraphX

### ISSUE THREAD

**Issue by umangyadav** [ROCm/AMDMIGraphX#1656]
### Motivation : 

MIGraphX can support multiple backend targets. It fully supports GPU target currently. It can target the CPU backend with limited functionality and FPGA support is in the BETA mode. Currently, MIGraphX can compile models for each of those individual backend targets. 

With a larger UIF common runtime goal, MIGraphX is a candidate to become a unified frontend for all the AMD (or even Intel/Nvidia) backends that includes FPGA, GPU, and CPUs. The goal is not limited to a single backend but it also should consider heterogeneous systems. That is MIGraphX should be able to compile models for combinations of different targets i.e. CPU + GPU, FPGA + CPU, GPU + FPGA,  FPGA + GPU + CPU, etc. 

We would name this heterogeneous compilation a `multi-target` compilation for the rest of the discussion. 

### Primer on IR structure of MIGraphX : 

Deep learning models from ONNX/TF are parsed into MIGraphX program. Each program consists of one `main` module and optionally several submodules. Modules can be also be nested. `main` is the root of module tree. 

Each module is made of up `instructions`. Each instruction is a "computation operator" or "node" in the computational graph.   Each instruction consumes other instructions as inputs thereby establishing a computational graph.

Modules are a grouping of instructions to aid in the compilation of programs. Modules are useful for defining control flow as well e.g. for the loop, IfThenElse operators. Another example is the pointwise module which helps in producing JIT kernels. 

### Pass manager : 
MIGraphX has two types of passes. 
	1. module pass 
	2. program pass.  

Module pass only runs pass on module v/s program pass applies the pass on the entire program.  

Currently, only the DeadCodeElimination is a program pass. The rest of the passes are module passes but they run on the main module so essentially making them program passes. 

### Multi-target Compilation :

`multi-target` compilation feature implementation can be broken down into the following few pieces :
	1. Graph partitioning 
		a. Target annotation
		b. (Proposed) Merge target regions 
	2. Subgraph compilation 

### Graph-partitioning : 

MIGraphX currently has a placeholder code for this process. 

The way it works right now is that : 

1. Each target would implement the `is_supported` function which would return True/False if it has an implementation for a particular instruction or not. 
2. Each target would also implement `find_supported` which would return `set<instruction>` from entire program for which it has support. 
3. Last step is partitioning where based on some pre-defined metrics (e.g. latency, throughput etc.) and based on requested compilation targets, it `get_target_assignments` would return annotate each instruction with target returning `map<instruction, target>` 
4. (Future)  Allow users to specify patterns of subgraph to over-ride automatic assignments.
5. (Future) allow users to specify target assignments for specific operators to over-ride automatic assignments.  

	
Thing to note is that target assignment is per instruction basis.  Instruction can also be control -flow instruction like IfThenElse which executes either Then module or Else module based on some condition.   In such cases target assignment for IfThenElse instruction doesn't apply to instructions inside either Then module or Else module. Target assignment is only valid for the `If` condition part.  Same applies to any sort of nesting of modules. 

### Merge-Compiler/backend regions : 
6. (Proposed) Graph partitioning should also merge instructions based on target assignments into modules based on some greedy algorithm to construct module which only consists of instructions for one target. 

- Switching from one target to another target requires synchronization, data transfers etc. Need to minimize that.  
- Case study of nested modules:  IfThenElse, Loop, SelectModule

Compiler should inject necessary copies and synchronization if execution switches from let's say GPU to FPGA within a module itself.  For now at this stage submodule can add  input parameters and `return`.  Memcpy and synchronization for those parameters and `return` can be handled based on supplied compile options at later stage. 
- Need to consider copying parameters from GPU to FPGA and vice-versa. 
	
After step 6 each submodule would have target assignment. Any child of that submodule can over-ride target parent's target assignment. 
	
### Subgraph compilation :

Let's defer cross-compilation for now. 

Users would provide compile_options as a `map<target, compile_options>` . Would call `compile()` on the program.  

(Future) Also, need the option to query available backends on a given system and do automatic multi-target. 

MIGraphX would fetch `vector<pass>` for each target and run those passes on each submodule based on its target. 

AFAIK, MIGraphX  is not doing any inter-module optimization, but it does nested module optimizations.  So even if GPU submodules are not contiguous in Program is for example: `FPGA --> GPU --> CPU --> GPU`, it should be fine. So, I don't see need to create a GPU_ROOT module or  FPGA_ROOT module. 
For example : 

- 	Memory Coloring : Don't need to worry about inter-module allocation. Allocation would only be valid for one module. When execution switches from GPU to FPGA  as part of nesting of modules (e.g.IfThenElse) then allocations should remain live but once execution comes back to GPU and finishes entirely, then allocation can be invalidated.  And next GPU module should do fresh allocation. 
- 	Scheduling : Same as memory coloring. Scheduling only needs to consider one (nested) submodule at a time.
- 	FuseOps : Can't do inter-module fusion. 

How to evaluate each separate module ? 
May need to add `mod_run_op` to facilitate execution. May not be necessary if MIGraphX injects Memcpy/synchronization in correct places. 
Modify `eval()` function to  use different context based on target assignments. 

I'll add more details as it goes.

**Comment by umangyadav** [comment]
@pfultz2 @hgaspar @varunsh-xilinx @woinck  Feel free to put comments, refute, and refine my arguments/proposal. 

I don't have everything covered but I'll add more details as it goes.

**Comment by pfultz2** [comment]
> How to evaluate each separate module ?

The op is mainly a placeholder that will run the submodule:

```cpp
struct run_on_target
{
    argument compute(const shape&,
                     const std::vector<argument>& args,
                     const std::vector<module_ref>& mods,
                     const std::function<std::vector<argument>(
                         module_ref&, const std::unordered_map<std::string, argument>&)>& run) const
    {
        module_ref mod = mods.front();
        std::unordered_map<std::string, argument> params;

        std::set<std::string> pnames = smod->get_parameter_names();

        assert(pnames.size() < args.size());
        std::transform(pnames.begin(),
                       pnames.end(),
                       args.begin() + 1,
                       std::inserter(params, params.end()),
                       [](auto&& name, auto&& arg) { return std::make_pair(name, arg); });

        auto results = run(mod, params);
        return argument{results};
    }
};
```

In the future, we will remove this placeholder op and inline the instructions in the main module so they can be interleaved with instructions from different targets.

> May not be necessary if MIGraphX injects Memcpy/synchronization in correct places.

We need some methods add to target to return a model which will insert the correct copies and synchronization instructions.

> Modify eval() function to use different context based on target assignments.

At the end of the compilation we need to mark each instruction with the target it will run on, so `eval()` can get the correct `context`.

**Comment by pfultz2** [comment]
> MIGraphX has two types of passes.
> 1. module pass
> 2. program pass.

There is actually another pass which takes the `module_pass_manager` and it can do things like retrieve the parent module, create modules, and run additional passes on the module.

For multi-target, we will want to also add a method to check if its a root module as some passes like `replace_allocate` need to know this, and we dont want a pass just checking if the name of the module is `main`(like what is done in `replace_allocate`).

> Currently, only the DeadCodeElimination is a program pass. The rest of the passes are module passes but they run on the main module so essentially making them program passes.

I plan to remove program passes as its problematic to run such pass with multi-targets. Only DCE pass uses the program pass to remove unused modules, but I think we can just have the pass manager remove unused modules implicitly after each pass.

**Comment by umangyadav** [comment]
> I consider this target assignments and partitioning as taking the assignments and putting them into seperate subgraphs.

Right now it is not creating any submodules based on target assignments. 

How do you define a Root module for a target? 

```cpp
// Gather all the target roots
std::unordered_multimap<std::string, module_ref> roots;
for(const auto& ins:p.get_main_module())
{
    if (ins.name() != "run_on_target")
        continue;
    auto v = ins.get_operator().to_value();
    module_ref root = ins.module_inputs().front();
    roots[v.at("target").to<std::string>()] = root;
}
```
It seems to me, there can be multiple root modules which is what I'd imagined. If there are multiple root modules. It shouldn't be called a `root` module. It is confusing. By "root", I would imagine there would only be one GPU module for the entire program. 

>    v.at("target").to<std::string>()

This is similar to annotating each module with a `target` flag. 

```cpp
// Run passes on each root target
for(const auto& t:targets)
{
    for(auto root:roots.equal_range(t.name()))
        run_passes(*this, root, t.get_passes(), trace);

}
```
It is running passes on each submodule individually.  It is confusing to say it runs on each "root" target if there can be multiple roots. 

> At the end of the compilation we need to mark each instruction with the target it will run on, so eval() can get the correct context.

`run_on_target` already has a `target` flag.  So I don't find marking each instruction necessary unless we inline all instructions and don't rely on `run_on_target`. 

> This is true, but I think for the first iteration we can just have the branches inherit the assignments to make it simpler. 

It can inherit, but should also be able to override that.

**Comment by umangyadav** [comment]
multi-target compile design assumes right now that `run_on_target` instructions have been added by the partitioner already. 

Which is not the case right now. That needs some work.

**Comment by pfultz2** [comment]
> How do you define a Root module for a target?

A module that doesnt have a parent with the same target. I dont see how this implies one root per target.

> So I don't find marking each instruction necessary unless we inline all instructions and don't rely on run_on_target.

Yes in the future we will inline(and interleave) the instructions. We need to in order to implement pipelining.

> It can inherit, but should also be able to override that.

Yes, but to override that we need a more complicated partitioning so that a module is either a single target or it has `run_on_target` operators. We dont need to worry about it for now, and what we are doing wont prevent us to support a more complicated partitioning.

**Comment by pfultz2** [comment]
> How would it know it is unused?

We know its not used there is no instruction that uses the module as input. The function `generic_get_unused_modules` in program.cpp will get the unused modules.

> If It can know it is unused, DCE can also know it is unused. If there is a way to keep global use count, DCE should be fine.

Right now, DCE just calls `prog.remove_unused_modules()`. We can just move that call to `run_passes`. I dont see a valid use case where we would want to keep an unused module in the graph. If there were we could easily add a flag to the module to keep it around even if its not referenced.

There a valid uses cases where you would keep an instruction around even if you dont use the output because instructions can have side effects. I just dont see such a case with modules.

Having a program pass can allow inadverdently passes from one target to affect the subgraph meant for a different target. By removing this type pass we can get better isolation for multi-target compilation.

**Comment by pfultz2** [comment]
> multi-target compile design assumes right now that run_on_target instructions have been added by the partitioner already.

The compile function will need to take the assignments and partition them into subgraphs. We can skip this for now to get started, but from a user perspective they would call `prog.compile({gpu{}, cpu{}}, assignments)`. Also the user can call without the assignments as `prog.compile({gpu{}, cpu{}})` which this compile will need to call `get_target_assignments`.

**Comment by umangyadav** [comment]
> prog.compile({gpu{}, cpu{}}, assignments) 

It also need to take compile options. First parameter could be `map<string, compile_options>`.

**Comment by umangyadav** [comment]
- [ ] Need to update MIGRAPHX_TRACE_COMPILE flag to take target value

**Comment by causten** [comment]
shelving for now
