### ISSUE TITLE
MLIR build failure in MIGraphX on Ubuntu 22.04

### ISSUE THREAD

**Issue by krzysz00** [ROCm/AMDMIGraphX#2123]
The Ubuntu 22.04 failure linked in https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/1081 ( logs at http://rocm-ci.amd.com/job/compute-parallel-build-stage2libs/26342/artifact/logs/amdmigraphx_failed.log ) was, per discussion with @pfultz2 , a bug in MIGraphX.

While I have reproduced and resolved the SLES issues, I have been unable to reproduce the Ubuntu 22.04 failure (as shown in the ticket).

@jerryyin @causten for who's going to do the MIGraphX fix.

**Comment by causten** [comment]
Fixed with #2138
