### ISSUE TITLE
New models for CI Performance and Accuracy

### ISSUE THREAD

**Issue by causten** [ROCm/AMDMIGraphX#2202]
Add ORT and MLPerf generated models to CI

- [ ] bert_base_cased_1_fp16_gpu.onnx
- [ ] bert_large_uncased_1_fp16_gpu.onnx
- [ ] distilgpt2_1_fp16_gpu.onnx
- [ ] resnet50_v1.onnx https://zenodo.org/record/4735647/files/resnet50_v1.onnx
- [ ] bert-large https://zenodo.org/record/3733910
- [ ] Create a list of models recommended to be removed from CI

**Comment by ahsan-ca** [comment]
From `performance_tests.sh`:
- [ ] bert_base_cased_1_fp16_gpu.onnx
`bert_base_cased_fp16         64 bert/bert_base_cased_1_fp16_gpu.onnx --fill1 input_ids --input-dim @input_ids 64 384 --batch 64`

- [ ] bert_large_uncased_1_fp16_gpu.onnx
`bert_large_uncased_fp16      32 bert/bert_large_uncased_1_fp16_gpu.onnx --fill1 input_ids --input-dim @input_ids 32 384 --batch 32`

- [ ] distilgpt2_1_fp16_gpu.onnx
`distilgpt2_fp16              16 distilgpt2/distilgpt2_1_fp16_gpu.onnx --fill1 input_ids --input-dim @input_ids 16 384 --batch 16`

- [ ] resnet50_v1.onnx https://zenodo.org/record/4735647/files/resnet50_v1.onnx
`resnet50v1_fp16               1 resnet50/resnet50_v1.onnx --fp16`

- [ ] bert-large https://zenodo.org/record/3733910
`bert_large_fp16               1 bert/model.onnx --fill1 input_ids --fill1 input_mask --fill1 segment_ids --fp16`

- [ ] Create a list of models recommended to be removed from CI
From chat with Umang (being removed under https://github.com/ROCm/AMDMIGraphX/issues/2400):
```
1. slim-vgg_1
2. slim-resnet50_v2_64
3. slim-mobilenet_1
4. torchvision-inceptionv3_1
```

**Comment by ahsan-ca** [comment]
Looks like we already have these models in CI.
@umangyadav can you please confirm if there is anything to do here that I might be missing? If not, I can close this issue. Thanks!

**Comment by umangyadav** [comment]
@ahsan-ca  Thanks for taking a look at this. Closing this issue.
