### ISSUE TITLE
parse_graph: Unknown operator: Einsum

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#2391]
MIGraphX does not support Einsum

**Comment by causten** [comment]
no it does not.  Is there a particular model that you are interested in?

**Comment by qianqing13579** [comment]
model link: https://drive.google.com/file/d/1T7qOqW8Nt_dLawg2Kij7akR3eEnaFpWI/view?usp=sharing

**Comment by taylding-amd** [comment]
Hi @qianqing13579 , einsum operator is added in ROCm 6.2: https://github.com/ROCm/AMDMIGraphX/blob/develop/CHANGELOG.md?plain=1#L15
