### ISSUE TITLE
[FP8] add autocast_fp8 pass for the  Python API

### ISSUE THREAD

**Issue by umangyadav** [ROCm/AMDMIGraphX#2447]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2438/files/dfb35a6879eaaf43e487e9b0e0ff7d3e1c2043bc#r1394731248

See this comment. 

Allow users to create numpy buffer in FP8 and parse them into MIGraphX's FP8 dtype using pybind interface. 
Add tests inside MIGraphX for the same.

**Comment by umangyadav** [comment]
https://reviews.llvm.org/D140746

**Comment by umangyadav** [comment]
After investigating into other frameworks looks like there  is no standard way to represent fp8 tensors in python. 

Brief survey is as here : 
•	Numpy doesn't have support for FP8
•	Python doesn't have native FP8
•	TensorRT doesn't have support for FP8 in API yet. they will announce it in future. They have some placeholders.
•	PyTorch has it. but they use `torch.tensor` with dtype=fp8
•	MLIR : I saw something in MLIR that [uses pybind](https://reviews.llvm.org/D140746) but I don't understand it enough.
•	Nvidia TransformerEngine has this [fp8.p](https://github.com/NVIDIA/TransformerEngine/blob/release_v0.12/transformer_engine/pytorch/fp8.py#L453)y and they use context manager that autocasts to fp8 and back.  
•	TVM : It is using "ml_dtypes" package https://pypi.org/project/ml-dtypes/ with which you can actually create numpy arrays with FP8 dtypes.      https://github.com/jax-ml/ml_dtypes Sounds more intuitive to me to use that from user perspective. This package also has support for BF16 and (int4 probably).  They also have PR for MX-types.


Plan is as follows:

1. create `autocast_fp8` pass that  modifies the parsed migraphx program to add converts from fp32 to fp8 for the inputs and outputs. there are 4 different types of fp8. autocast_fp8 should convert to fp8 type that is in the model.  It could be similar to `eliminate_fp8` pass that i have here. https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/rocblas_fp8/src/eliminate_fp8.cpp
3. expose this pass an API in Python ( and c++ if required). 
4. add some tests.

**Comment by umangyadav** [comment]
4. Enabled ONNX python backend test. See this comment here : https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2493#issuecomment-1836217212

**Comment by ahsan-ca** [comment]
Draft PR converted to actual PR with all the required functionality and tests. PR is up for review: https://github.com/ROCm/AMDMIGraphX/pull/2527
