### ISSUE TITLE
Segmentation fault during compiling FP16 MaskRCNN 

### ISSUE THREAD

**Issue by gyulaz-htec** [ROCm/AMDMIGraphX#2465]
MiGraphX version: 241488570d3d58312ed628edd84101a5074aaa42
Model: [MaskRCNN-12.onnx](https://github.com/onnx/models/blob/main/validated/vision/object_detection_segmentation/mask-rcnn/model/MaskRCNN-12.onnx)
Command: `migraphx-driver compile --fp16 MaskRCNN-12.onnx --input-dim @image 3 800 800​`
This will fail with a segmentation fault on this [line](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/241488570d3d58312ed628edd84101a5074aaa42/src/simplify_reshapes.cpp#L292) in `find_concat_multibroadcasts`, because the value of `op.axis` is negative. Because of the negative value `in_strides.begin() + op.axis` points to an unknown memory address and causes a segfault.

**Comment by pfultz2** [comment]
We need to add normalization to the broadcast operator. I think something like `value::array{normalize_attribute::include_min}` should be equivalent.

**Comment by gyulaz-htec** [comment]
@pfultz2 I've tried your suggestion added this to the boradcast op:
```cpp
    value attributes() const
    {
        value normalize;
        normalize["axis"] = value::array{normalize_attribute::include_min};
        return {{"normalize_axes", normalize}};
    }
   ```
   but it didn't solve the issue.
  
I continued looking into it in more detail. For me it looks like the bug comes from these two [lines](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/optimize_module.cpp#L42-L43) in the `optimize_module` pass:
```cpp        
        // loop to further optimize after initial transformations
        for(int j = 0; j < 2; j++)
        {
            mpm.run_pass(simplify_reshapes{});
            mpm.run_pass(simplify_algebra{});
        }
```
From my findings `simplify_algebra` pass can insert a `concat` with a negative `axis` value [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/d3e5a5c0f386f22c6c81c2dca9158b336127f3db/src/simplify_algebra.cpp#L724).
When the for loop goes to the next iteration `simplify_reshapes` picks up that `concat` and crashes on this [line](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/241488570d3d58312ed628edd84101a5074aaa42/src/simplify_reshapes.cpp#L292) due to the negative `axis`:
```cpp
op.axis -= std::count(in_strides.begin(), in_strides.begin() + op.axis, 0);
```

My suggestion is to add a `normalize_ops` pass after `simplify_algebra` in the problemtaic for loop:
```cpp
        // loop to further optimize after initial transformations
        for(int j = 0; j < 2; j++)
        {
            mpm.run_pass(simplify_reshapes{});
            mpm.run_pass(simplify_algebra{});
            mpm.run_pass(normalize_ops{});
            mpm.run_pass(dead_code_elimination{});
        }
```
This fixed the issue on my side and made the compilation go further. @pfultz2  what do you think about it?

**Comment by gyulaz-htec** [comment]
@pfultz2 I had another round with this.
I made a mistake stating the the concat comes from the `simplify_algebra` pass.
The concat with `-1` `axis` is loaded from the model:

![concat](https://github.com/ROCm/AMDMIGraphX/assets/126694206/4b2c05b0-e0dc-4dc1-aef8-1ad6d6430508)

The main source of the issue is that there is no normalization done before calling [quantize_fp16](https://github.com/ROCm/AMDMIGraphX/blob/develop/src/quantization.cpp#L55-L61) when compiling with `--fp16`. 
In this case I still think adding the `normalize_ops` pass somewhere before the `simplify_reshapes` would be the proper solution.
