### ISSUE TITLE
Gelu investigation

### ISSUE THREAD

**Issue by causten** [ROCm/AMDMIGraphX#2485]
word is CK has a faster gelu than migx version.  try to add it

**Comment by CharlieL7** [comment]
This issue is linked to: #2542

**Comment by lakhinderwalia** [comment]
Closing this, as changes done in [CK](https://github.com/ROCm/composable_kernel/pull/1162) are reflected in https://github.com/ROCm/AMDMIGraphX/issues/2542 -- which I have reviewed.
