### ISSUE TITLE
Add `eliminate_nested_converts` pass and add unit-tests

### ISSUE THREAD

**Issue by umangyadav** [ROCm/AMDMIGraphX#2520]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2506#discussion_r1416435324

`eliminate_data_type` pass requires removal of nested converts and 
there is already a matcher inside `simplify_reshapes` that does exactly that.  need to move this matcher into a separate pass and use that instead. 

Add unit-tests . Unit-tests should cover cases like those described in #2517

Some initial work is already here : https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/compare/quant_gemm_fp8...eliminate_nested_converts?expand=1

**Comment by CharlieL7** [comment]
Working on this, fixing bug

**Comment by umangyadav** [comment]
@CharlieL7  is this fixed ?

**Comment by umangyadav** [comment]
Fixed with https://github.com/ROCm/AMDMIGraphX/pull/2525/files#diff-25ecf97dd6d0374c3b442647c1d8bdcb48be882a5842ccccff7e15409572081a
