### ISSUE TITLE
I want to ask if MIGraphX support Llama2 model?

### ISSUE THREAD

**Issue by sunpian1** [ROCm/AMDMIGraphX#2552]
I want to ask if MIGraphX support Llama2 model?

**Comment by pfultz2** [comment]
Here is a PR to for a llama2 example you could follow:

https://github.com/ROCm/AMDMIGraphX/pull/2521

**Comment by sunpian1** [comment]
thanks

**Comment by sunpian1** [comment]
I will wait until this PR is merged.

**Comment by sunpian1** [comment]
i wonder whether you can help me with another question.[https://github.com/ROCmSoftwarePlatform/DeepSpeed/issues/68](url)

**Comment by causten** [comment]
> i wonder whether you can help me with another question. [ROCmSoftwarePlatform/DeepSpeed#68](https://github.com/ROCmSoftwarePlatform/DeepSpeed/issues/68)

One question per PR, but I did reach out to a person on the DeepSpeed repo to comment

**Comment by sunpian1** [comment]
thanks,@causten

**Comment by sunpian1** [comment]
@causten, who is that person?could you give me his or her email to contact him or her?

**Comment by causten** [comment]
> @causten, who is that person?could you give me his or her email to contact him or her?

Check the PR, it's the owner of https://github.com/ROCm/AMDMIGraphX/pull/2521
