### ISSUE TITLE
Resize matcher for dynamic batch support

### ISSUE THREAD

**Issue by bpickrel** [ROCm/AMDMIGraphX#2658]
Create a matcher and optimization pass to change "resize" operations to a combination of Reshape and Gather.  This is a prerequisite for processing Resize operations from Onnx models with dynamic batch size OR runtime scale/size input, because there is not a direct Resize implementation for the GPU target yet.

This takes advantage of the fact that at the time of optimization, the previously undetermined output dimensions are now known and the necessary indexes for the Gather op. can be calculated.

**Comment by qianqing13579** [comment]
@bpickrel , you can develop a dynamic Resize kernel implementation for the GPU target. Here is a ref impl. the parse_resize.hpp is [here](https://github.com/qianqing13579/MIGraphX_Dynamic/blob/master/src/onnx/parse_resize.cpp)，and the gpu kernel implemention is [here](https://github.com/qianqing13579/MIGraphX_Dynamic/blob/master/src/targets/gpu/device/upsample.cpp)

**Comment by bpickrel** [comment]
> @bpickrel , you can develop a dynamic Resize kernel implementation for the GPU target. Here is a ref impl. The gpu kernel implemention is [here](https://github.com/qianqing13579/MIGraphX_Dynamic/blob/master/src/targets/gpu/device/upsample.cpp)

Excellent.  This change is a short-term fix until that is integrated.  With this one, and two other PRs that are in review, we should be able to perform inference on certain models including Yolov5 with dynamic batch size inputs.

**Comment by CharlieL7** [comment]
> @bpickrel , you can develop a dynamic Resize kernel implementation for the GPU target. Here is a ref impl. The gpu kernel implemention is [here](https://github.com/qianqing13579/MIGraphX_Dynamic/blob/master/src/targets/gpu/device/upsample.cpp)

We're not planning to make a dynamic Resize operator that runs on the GPU for this issue. We're open to reviewing and adding that to the codebase though. Please open a PR or discussion if you're interested in doing so.
