### ISSUE TITLE
DLM Pass for Bert-Base with Squad v1.1 dataset

### ISSUE THREAD

**Issue by TedThemistokleous** [ROCm/AMDMIGraphX#2664]
Add DLM pass for Bert-base model pretrained on the squad v1.1 dataset found here:
https://zenodo.org/records/3733910

This requires the following be handled

- [x] Sequence length 384
- [x] Batch size sweep 1-256 in powers of 2

**Comment by TedThemistokleous** [comment]
It appears this can leverage the existing bert tests we already have using the eval_squad.py script.

**Comment by TedThemistokleous** [comment]
Scrapped work with eval_squad.py. Seems to be a giant pain (square peg round hole scenario) to get this to work. 

Instead I've been able to leverage an example in the onnxruntime-inference-examples repo performed by TRT. 

Reading dataset is done. Total examples is 10570

```
Output dump to ./prediction.json
Evaluate QDQ model for SQUAD v1.1
&&&& PASSED MIGraphX BERT Squad Accuracy matches reference.
{"exact_match": 83.68968779564806, "f1": 90.87487229720105}
```

Added a bit more args to this to fine tune before I commit and attempt additional batch sizes for the desired parts Perf is asking for.

```
usage: e2e_migraphx_bert_example.py [-h] [--fp16] [--int8] [--model] [--version VERSION] [--batch BATCH] [--seq_len SEQ_LEN] [--doc_stride DOC_STRIDE] [--cal_num CAL_NUM] [--verbose]

options:
  -h, --help            show this help message and exit
  --fp16                Perform fp16 quantization on the model before running inference
  --int8                Perform int8 quantization on the model before running inference
  --model               Path to the desired model to be run. Default ins ./model.onnx
  --version VERSION     Squad dataset version. Default is 1.1. Choices are 1.1 and 2.0
  --batch BATCH         Batch size per inference
  --seq_len SEQ_LEN     sequence length of the model. Default is 384
  --doc_stride DOC_STRIDE
                        document stride of the model. Default is 128
  --cal_num CAL_NUM     Number of calibration for QDQ Quantiation in int8. Default is 100
  --verbose             Show verbose output

```
Should make evaluating this script in the DLM hooks easier. Seems like Nvidia likes to just bake things in instead of trying to add a configurable input that can be run via CLI. I symlinked the desired MLPerf model on the NAS and got the above inference. Seems like we can reuse this example to test various flavors of Bert with the squad dataset easily across quantization levels

Will need to update the DLM side for this to work.

**Comment by TedThemistokleous** [comment]
Script complete. Seeing odd behavior at larger batch sizes with additional samples. 
Updated the input args to adjust the amount of samples and turn off the validation to perform an f1 score for now till I get to the bottom of things.

Able to run this for squad v1.1 and v2.0 thanks to leveraging the TRT script. Need to validate if int8 works here as well but that isn't the priority. 

DLM changes up for review now

**Comment by TedThemistokleous** [comment]
Having issues with the upstream NAS still with getting this to run.

**Comment by TedThemistokleous** [comment]
Got models uploaded and access to upload to our S3 instance. Waiting for CI now. Should be closed out EOD

**Comment by zixianwang2022** [comment]
Hi @TedThemistokleous , 

I am Zixian Wang from UCSD, participating [Student Cluster Competition](https://sc24.supercomputing.org/students/student-cluster-competition/) that will be held as SC24. I am currently looking into how to run MLPerf Stable Diffusion XL Inference's Tensor-RT implementation onto using MIGraphX for AMD GPUs. Is it possible to learn some insights from you regarding this effort please? 

Thank you! 
Zixian

**Comment by kahmed10** [comment]
> Hi @TedThemistokleous ,
> 
> I am Zixian Wang from UCSD, participating [Student Cluster Competition](https://sc24.supercomputing.org/students/student-cluster-competition/) that will be held as SC24. I am currently looking into how to run MLPerf Stable Diffusion XL Inference's Tensor-RT implementation onto using MIGraphX for AMD GPUs. Is it possible to learn some insights from you regarding this effort please?
> 
> Thank you! Zixian

This doesn't belong on this particular issue, but we have an SDXL example under examples/diffusion/python_stable_diffusion_xl directory that you can try out. Please open a new issue to continue the discussion.
