### ISSUE TITLE
Automate existing internal performance to run on different hardware

### ISSUE THREAD

**Issue by causten** [ROCm/AMDMIGraphX#2670]
MIGraphX has some internal performance tests (DLM), the request here is to run those same tests using other companies hardware.  DLM already has infrastructure to launch cudnn in a container.  The change here is to change the ./scripts/migx* files to support TRT runs.  There are lots of examples in the DLM repo where an `if` check is done to determine the correct syntax to use.

Models to automate:
mlperf/resnet50_v1.onnx --batch 1
mlperf/resnet50_v1.onnx --batch 64
ORT/bert_base_cased_1.onnx  --fill1 input_ids --input-dim @input_ids 1 384
ORT/bert_base_cased_1.onnx  --fill1 input_ids --input-dim @input_ids 64 384 --batch 64
ORT/onnx_models/bert_large_uncased_1_fp16_gpu.onnx  --fill1 input_ids --input-dim @input_ids 1 384
ORT/onnx_models/bert_large_uncased_1_fp16_gpu.onnx  --fill1 input_ids --input-dim @input_ids 32 384 --batch 32
ORT/onnx_models/distilgpt2_1_fp16_gpu.onnx  --fill1 input_ids --input-dim @input_ids 1 384
ORT/onnx_models/distilgpt2_1_fp16_gpu.onnx  --fill1 input_ids --input-dim @input_ids 16 384 --batch 16
sd21-onnx/unet/model.onnx --input-dim @sample 2 4 64 64 @timestep 1 @encoder_hidden_states 2 64 1024 --fp16
sd21-onnx/unet/model.onnx --input-dim @sample 8 4 64 64 @timestep 1 @encoder_hidden_states 8 64 1024 --fp16

**Comment by ahsan-ca** [comment]
Draft PR: https://github.com/ROCm/DeepLearningModels/pull/1229
Has changes for resnet50 and gpt2. Working on bertsquad-12.

**Comment by ahsan-ca** [comment]
TO DO: I need to update the model for resnet50 to be the same as the one run for mlir:`scripts/migx_mlir/run.sh`. Tried to use `$DLM_DATAHOME/mlperf/` path but could not get it to work on the machine I was testing this out on. Will come back to updating this once I have updated run scripts for all models.
