### ISSUE TITLE
BLAZE question

### ISSUE THREAD

**Issue by jinz2014** [ROCm/AMDMIGraphX#2681]
Can you please explain the removal of BLAZE ?   

Building the library may show the following error.
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/path/to/AMDMIGraphX-rocm-6.0.0/src/targets/ref/BLAZE_INCLUDE
```

Reference
src/targets/ref/CMakeLists.txt:find_path(BLAZE_INCLUDE blaze/Blaze.h)
src/targets/ref/CMakeLists.txt:target_include_directories(migraphx_ref PRIVATE ${BLAZE_INCLUDE})
src/targets/ref/CMakeLists.txt:target_compile_definitions(migraphx_ref PRIVATE -DBLAZE_USE_CPP_THREADS)

**Comment by pfultz2** [comment]
You need BLAZE installed to build migraphx from source. Please see our README on how to build migraphx from source.

**Comment by pfultz2** [comment]
What commit hash of migraphx are you building from?

**Comment by jinz2014** [comment]
I built the library before BLAZE was removed. Thanks.
