### ISSUE TITLE
Question about Import the MIGraphX module in Python script for a custom install location 

### ISSUE THREAD

**Issue by jinz2014** [ROCm/AMDMIGraphX#2700]
When the AMDMIGraphX library is not installed in the default location (e.g /opt/rocm), do users need to create .deb packages first to import the MIGraphX module in Python script ?

**Comment by tcgu-amd** [comment]
Hi @jinz2014 Thanks for reaching out, and sorry for the lack of responses. To answer your question, no a .deb package is not required.  Even if AMDMIGraphX is not installed in the default location, as long as the shared libraries are included in your `LD_LIBRARY_PATH` and `PYTHONPATH` points to the directory containing cpython bindings correctly, it should work.

To elaborate, let's say `migraphx` is installed through apt, then, under `/opt/rocm/lib` , you should find a cpython binding library `migraphx.cpython-38-x86_64-linux-gnu.so` and a directory called `migraphx` that contains the `include` and the `lib` subdirectories.

If you install `migraphx` to a custom directory `/my/path`, then you should find still find the cpython bindings at `/my/path/migraphx.cpython-38-x86_64-linux-gnu.so`.  You want to set the your PYTHONPATH to include this binding with 

```bash
export PYTHONPATH=$PYTHONPATH:/my/path
```
Next, let's say you have the libraries that that would normally be under `/opt/rocm/lib/migraphx/lib` installed at `/my/path/libs`, then you would want to update your LD_LIBARARY_PATH accrodingly with 

```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/my/path/lib
```

Finally, make sure you have the correct version of cpython bindings for your python verison. For example, `migraphx.cpython-38-x86_64-linux-gnu.so` will only work with python 3.8. 

Hope this helps!

**Comment by jinz2014** [comment]
Thank you for your answers!
