### ISSUE TITLE
Fully Convolutional Network (FCN) model verification fails with FP16

### ISSUE THREAD

**Issue by gyulaz-htec** [ROCm/AMDMIGraphX#2708]
[fcn-resnet101-11.onnx](https://github.com/onnx/models/blob/main/validated/vision/object_detection_segmentation/fcn/model/fcn-resnet101-11.onnx)  ONNX Zoo model fails with `driver verify --fp16`.

rocm version: 5.7.0.50700-63~20.04
migraphx version: 352dcea2c6a03c495a6ba8667e19811bc5d1399b

The output of `migraphx-driver verify validated/vision/object_detection_segmentation/fcn/model/fcn-resnet101-11.onnx --fp16`:
```bash
FAILED: vision/object_detection_segmentation/fcn/model/fcn-resnet101-11.onnx
RMS Error: 0.167497
Max diff: 3.72932
Mismatch at 0: 5.67143 != 8.05469

FAILED: vision/object_detection_segmentation/fcn/model/fcn-resnet101-11.onnx
RMS Error: 0.327091
Max diff: 7.21077
Mismatch at 0: 4.00074 != 6.64453
```

**Comment by attila-dusnoki-htec** [comment]
The problem is with the `reference` implementation. It **does not** support `dilation`: https://github.com/ROCm/AMDMIGraphX/blob/develop/src/include/migraphx/convolution.hpp#L38
And this model has `conv2d` with `dilation=[2,2]`.
