### ISSUE TITLE
Rewrite reshapes to improve const folding of mul_add

### ISSUE THREAD

**Issue by pfultz2** [ROCm/AMDMIGraphX#2736]
In unet, there is a pattern like this:

```
@218 = hip::hip_copy_literal[id=main:@literal:902] -> half_type, {640, 1, 1}, {1, 1, 1}
@219 = hip::hip_copy_literal[id=main:@literal:755] -> half_type, {640, 640}, {640, 1}
@220 = hip::hip_copy_literal[id=main:@literal:784] -> half_type, {640, 1, 1}, {1, 1, 1}
@224 = multibroadcast[out_lens={2, 640, 64, 64},out_dyn_dims={}](@220) -> half_type, {2, 640, 64, 64}, {0, 1, 0, 0}
@225 = reshape_lazy[dims={2, 640, 64, 64}](@223) -> half_type, {2, 640, 64, 64}, {2621440, 4096, 64, 1}
@226 = load[offset=62969600,end=73455360](@1) -> half_type, {2, 640, 64, 64}, {2621440, 4096, 64, 1}
@227 = multibroadcast[out_lens={2, 640, 64, 64},out_dyn_dims={}](@218) -> half_type, {2, 640, 64, 64}, {0, 1, 0, 0}
@228 = gpu::code_object[code_object=9352,symbol_name=mul_add_kernel,global=655360,local=1024,](@225,@227,@224,@226) -> half_type, {2, 640, 64, 64}, {2621440, 4096, 64, 1}
@229 = transpose[permutation={0, 2, 3, 1}](@228) -> half_type, {2, 64, 64, 640}, {2621440, 64, 1, 4096}
@230 = reshape_lazy[dims={2, 4096, 640}](@229) -> half_type, {2, 4096, 640}, {2621440, 1, 4096}
@231 = multibroadcast[out_lens={2, 640, 640},out_dyn_dims={}](@219) -> half_type, {2, 640, 640}, {0, 640, 1}
@232 = load[offset=140435200,end=150920960](@1) -> half_type, {2, 4096, 640}, {2621440, 640, 1}
@233 = gpu::gemm[alpha=1,beta=0,compute_fp32=1,trans_batch=0,solution_idx=0](@230,@231,@232) -> half_type, {2, 4096, 640}, {2621440, 640, 1}
```

We already have a pass to do the rewriting needed to const fold it(see [`find_dot_add`](https://github.com/ROCm/AMDMIGraphX/blob/4c4474b7882d315560cc386df74cac87a3d77f20/src/simplify_algebra.cpp#L366) and [`find_dot_mul`](https://github.com/ROCm/AMDMIGraphX/blob/4c4474b7882d315560cc386df74cac87a3d77f20/src/simplify_algebra.cpp#L269)), but it doesnt work with these extra operators between them and the gemm. To improve it we can:

- In simplify_reshapes, move the transpose+reshape to the input of multiply, and then adjust the broadcast for the constants to use the correct axis.
- We will still have an extra `multibroadcast` to broadcast the batch dimensions. This probably can't be removed so we will need adjust [`find_dot_add`](https://github.com/ROCm/AMDMIGraphX/blob/4c4474b7882d315560cc386df74cac87a3d77f20/src/simplify_algebra.cpp#L366) and [`find_dot_mul`](https://github.com/ROCm/AMDMIGraphX/blob/4c4474b7882d315560cc386df74cac87a3d77f20/src/simplify_algebra.cpp#L269) to account for an extra broadcast.

**Comment by shivadbhavsar** [comment]
@pfultz2 Why is the extra multibroadcast a problem for find_dot_add and find_dot_mul? They just look for a constant (which the multibroadcast ins is) and so it should still make the a*x + a*b simplification.

**Comment by pfultz2** [comment]
There is a multibroadcast on the A matrix, which is not a constant.

**Comment by pfultz2** [comment]
I see, the multibroadcast is on the inputs to mul_add only, and the other broadcast is on the constant, which doesnt matter for the simplification. So we only need to rewrite the transpose+reshape.
