### ISSUE TITLE
static_compute_shape: reshape_lazy on axis that is not packed

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [ROCm/AMDMIGraphX#2762]
- MIGraphX commit: [431e714](https://github.com/ROCm/AMDMIGraphX/commit/431e714ae6bd40e8793b5a2ab455bfbc45f1679e)
- GPU: MI210 (gfx90a)
- ROCm version: 6.0.1

Model(s) to reproduce:

- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_128_Opset16_timm/levit_128_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_128_Opset17_timm/levit_128_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_128s_Opset16_timm/levit_128s_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_128s_Opset17_timm/levit_128s_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_192_Opset16_timm/levit_192_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_192_Opset17_timm/levit_192_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_256_Opset16_timm/levit_256_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_256_Opset17_timm/levit_256_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_384_Opset16_timm/levit_384_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/levit_384_Opset17_timm/levit_384_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_b_Opset16_torch_hub/swin_b_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_b_Opset17_torch_hub/swin_b_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_b_Opset18_torch_hub/swin_b_Opset18.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window12_384_Opset16_timm/swin_base_patch4_window12_384_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window12_384_Opset17_timm/swin_base_patch4_window12_384_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window12_384_in22k_Opset16_timm/swin_base_patch4_window12_384_in22k_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window12_384_in22k_Opset17_timm/swin_base_patch4_window12_384_in22k_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window7_224_Opset16_timm/swin_base_patch4_window7_224_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window7_224_Opset17_timm/swin_base_patch4_window7_224_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window7_224_in22k_Opset16_timm/swin_base_patch4_window7_224_in22k_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_base_patch4_window7_224_in22k_Opset17_timm/swin_base_patch4_window7_224_in22k_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window12_384_Opset16_timm/swin_large_patch4_window12_384_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window12_384_Opset17_timm/swin_large_patch4_window12_384_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window12_384_in22k_Opset16_timm/swin_large_patch4_window12_384_in22k_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window12_384_in22k_Opset17_timm/swin_large_patch4_window12_384_in22k_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window7_224_Opset16_timm/swin_large_patch4_window7_224_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window7_224_Opset17_timm/swin_large_patch4_window7_224_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window7_224_in22k_Opset16_timm/swin_large_patch4_window7_224_in22k_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_large_patch4_window7_224_in22k_Opset17_timm/swin_large_patch4_window7_224_in22k_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s3_base_224_Opset16_timm/swin_s3_base_224_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s3_base_224_Opset17_timm/swin_s3_base_224_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s3_small_224_Opset16_timm/swin_s3_small_224_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s3_small_224_Opset17_timm/swin_s3_small_224_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s3_tiny_224_Opset16_timm/swin_s3_tiny_224_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s3_tiny_224_Opset17_timm/swin_s3_tiny_224_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s_Opset16_torch_hub/swin_s_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s_Opset17_torch_hub/swin_s_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_s_Opset18_torch_hub/swin_s_Opset18.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_small_patch4_window7_224_Opset16_timm/swin_small_patch4_window7_224_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_small_patch4_window7_224_Opset17_timm/swin_small_patch4_window7_224_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_t_Opset16_torch_hub/swin_t_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_t_Opset17_torch_hub/swin_t_Opset17.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_t_Opset18_torch_hub/swin_t_Opset18.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_tiny_patch4_window7_224_Opset16_timm/swin_tiny_patch4_window7_224_Opset16.onnx
- https://github.com/onnx/models/tree/ddbbd1274c8387e3745778705810c340dea3d8c7/Computer_Vision/swin_tiny_patch4_window7_224_Opset17_timm/swin_tiny_patch4_window7_224_Opset17.onnx

Fails at: `/code/AMDMIGraphX/src/include/migraphx/op/reshape_lazy.hpp:285: static_compute_shape: reshape_lazy on axis that is not packed.`

**Comment by gyulaz-htec** [comment]
https://github.com/ROCm/AMDMIGraphX/pull/2721 most probably fixes these as it did for other ONXX Zoo models. We have to run a check on these models with that change included.

**Comment by attila-dusnoki-htec** [comment]
The above mentioned PR fixed it.
