### ISSUE TITLE
Investigate CI UT Navi lockup

### ISSUE THREAD

**Issue by causten** [ROCm/AMDMIGraphX#2774]
In order to get Navi HW in to CI we need to determine why we get CI timeouts

**Comment by TedThemistokleous** [comment]
The more I poke at this the more I think this isn't an MIGraphX issue and something lower level. I've updated the jira ticket with my findings after trying to hammer this issue from a few different angles, as well as speaking to different engineers. I can't even get rocgdb to work correctly to get a stack trace and there seems to be some variable load element as well. AMD logging isn't giving me much and the addresses that fail don't trace back to any threads/streams we're trying to free/destroy/cleanup

**Comment by TedThemistokleous** [comment]
This isn't an MIGraphX Issue. Ive pushed this to KFD team + Firmware. Seeing multiple other issues occurring on the system at the driver/kernel level and the issue isn't related to MIGraphX after attempting to run builds off baremetal.

**Comment by TedThemistokleous** [comment]
Lockup appears to be solved with new driver/firmware. Awaiting update from other issues seen from Teddy / Kernel teams. Closing this out for now
