### ISSUE TITLE
`multibroadcast` `output_lens` attribute misnomer

### ISSUE THREAD

**Issue by CharlieL7** [ROCm/AMDMIGraphX#2790]
* When we use `multibroadcast` in MIGX the `output_lens` attribute is actually meant to be the other shape that we're broadcasting the input tensor with. It is **not** the dimensions of the output shape of the operator.
* We should rename the attribute to something like `broadcast_dims` to make the intent more clear.

Example of mixed meaning:
```
Want to broadcast a {2} tensor into a {3, 2} tensor

x has shape with lens = {2}
multibroadcast( x, output_lens = {3, 2} )  <-- this will throw

The correct call:
multibroadcast( x, output_lens = {3, 1} )  <-- passes
```

**Comment by pfultz2** [comment]
The `out_lens` is the dimensions of the output shape. We pass it directly to the shape:

https://github.com/ROCm/AMDMIGraphX/blob/79a025fc9a284dec77b0dd4f23e04bf8cd14f9c0/src/include/migraphx/op/multibroadcast.hpp#L104

Furthermore, what you are suggesting doesnt work. This program fails with `input shape {2} cannot be broadcasted to {3, 1}!`:

```python
p = migraphx.program()
m = p.get_main_module()
x = m.add_literal(migraphx.generate_argument(migraphx.shape(type="float_type", lens=[2]), 0))
xb = m.add_instruction(migraphx.op("multibroadcast", out_lens=[3, 1]), [x])
```

Also, I find this behavior surprising, and it would be inconsistent with the `broadcast` operator.

**Comment by CharlieL7** [comment]
Figured out my confusion, had a change locally that broke some things. Closing
