### ISSUE TITLE
Support SoftmaxCrossEntropyLoss

### ISSUE THREAD

**Issue by hgaspar** [ROCm/AMDMIGraphX#2976]
This is a very common ONNX operator.

ORT falls back to CPU when encountering this node.  The code is at:

https://github.com/microsoft/onnxruntime/blob/ee603ee3265dbf6eac112baf273b6b69bf696085/onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc#L1022-L1029

This happens when executing LLama v2, from:

https://github.com/microsoft/onnxruntime-inference-examples/blob/main/python/models/llama/LLaMA-2 E2E Notebook.ipynb

**Comment by TedThemistokleous** [comment]
Relevant doc/spec - https://github.com/onnx/onnx/blob/main/docs/Operators.md#softmaxcrossentropyloss
