### ISSUE TITLE
AMD GPUs cloud instances for MIGraphX development

### ISSUE THREAD

**Issue by aditya-167** [ROCm/AMDMIGraphX#2981]
Hi,
I would like to contribute to ROCm/MIGraphX.. however I dont have AMD gpu. I tried with AWS EC2 G4 (it has only AMD Radeon Pro V520 instance) which doesnt support ROCm. Kindly let me know if any another available cloud instances support ROCm?.

**Comment by kahmed10** [comment]
Please stay tuned... Azure has MI300X instances on preview mode currently. Alternatively, you could try building the CPU version. That way if you want to contribute to overall improvements to the graph compiler, you still are able to.

**Comment by aditya-167** [comment]
very well, thanks!
