### ISSUE TITLE
packed_or_broadcasted: gpu::mlir_op: Shapes are not packed nor broadcasted

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/AMDMIGraphX#3005]
Torch benchmarks fail.
Affected models:
TIMM: xcit_large_24_p8_224
HF: MobileBertForQuestionAnswering, MobileBertForMaskedLM

**Comment by CharlieL7** [comment]
Issue is with `find_reduce_reduce` matcher. Sometimes it gives the mentioned error, sometime it's a seg fault. Investigating what is the cause of the issue.

**Comment by pfultz2** [comment]
Does #3039 fix this issue?

**Comment by CharlieL7** [comment]
#3039 does get around the `packed_or_broadcasted` error. Now has a seg. fault in `gpu::compile_ops`

**Comment by CharlieL7** [comment]
#3070 fixes the seg fault
