### ISSUE TITLE
static_compute_shape: Reshape: Wrong number of elements for reshape

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/AMDMIGraphX#3006]
Torch benchmarks fail.
Affected models:
Torchbench: BERT_pytorch

**Comment by shivadbhavsar** [comment]
Unable to reproduce with latest develop branch

**Comment by bpickrel** [comment]
New error:  
```
cuda eval  BERT_pytorch                       
python: /workspace/pt2_benchmarks/AMDMIGraphX/src/include/migraphx/any_ptr.hpp:61: T migraphx::any_ptr::get() const [T = ihipStream_t *]: Assertion `ptr != nullptr' failed.
ERROR
```

**Comment by bpickrel** [comment]
The above appears to be due to an unknown configuration error.  Ran the same script in a different docker container and it completed without error.
