### ISSUE TITLE
[Feature]: Support Stable Diffusion 3 to run automatically

### ISSUE THREAD

**Issue by causten** [ROCm/AMDMIGraphX#3200]
Description Checklist

- [x]  Get reference model
- [x]  Model uploaded to nas mount
- [x]  Capture model for Performance review
- [x]  Capture TensorRT execution
- [ ]  Add benchmark in DLM for both MIGX and TRT

**Comment by zixianwang2022** [comment]
Hi @causten @kahmed10 , 

I am trying to run MLPerf Inference on Stable Diffusion XL. I am currently investigating Nvidia's TensorRT's build. 
Do you know if I can directly change TensorRT driver to MIGraphX, such that I can run it on Instinct GPUs?
