### ISSUE TITLE
Bump CI to 6.2 once released

### ISSUE THREAD

**Issue by causten** [ROCm/AMDMIGraphX#3318]
Update our [Dockerfile ](https://github.com/ROCm/AMDMIGraphX/blob/develop/Dockerfile) and [hip-clang.docker](https://github.com/ROCm/AMDMIGraphX/blob/develop/hip-clang.docker) 

Additional files may also be needed https://github.com/ROCm/AMDMIGraphX/tree/develop/tools/docker

**Comment by TedThemistokleous** [comment]
Are we going to still do the change for 6.1 in the meantime?

**Comment by TedThemistokleous** [comment]
Waiting for 6.1.3 CI update changes till I retry this again
