### ISSUE TITLE
Segmentation fault - MobileNetV2

### ISSUE THREAD

**Issue by CharlieL7** [ROCm/AMDMIGraphX#3355]
* We're getting a segmentation fault when running a TorchMIGraphX test `pytest fx/models/test_lowering_fx.py::test_vision_model[model=MobileNetV2-rtol=0.003-atol=0.01]` with the latest code in develop MIGraphX.
* It's commit between my bitwise_and operator #3321 and constraints to type-erased class constructors #3333

**Comment by umangyadav** [comment]
@CharlieL7  can you provide reproduction steps and also have you build it with debug build ?

**Comment by CharlieL7** [comment]
> @CharlieL7 can you provide reproduction steps and also have you build it with debug build ?

Let me try to get a more minimal example using the driver instead of TorchMIGraphX

**Comment by CharlieL7** [comment]
[MobileNetV2.zip](https://github.com/user-attachments/files/16565813/MobileNetV2.zip)
Ran it with driver in debug, here's the output: 
```
Running [ MIGraphX Version: 2.11.0. ]: bin/driver run /codes/onnx_models/MobileNetV2.onnx
Compiling ...
Reading: /codes/onnx_models/MobileNetV2.onnx
driver: /codes/3_AMDMIGraphX/src/pass_manager.cpp:131: virtual void migraphx::module_pm::run_pass(const pass &): Assertion `mod->validate() == mod->end()' failed.
Aborted (core dumped)
```

**Comment by umangyadav** [comment]
I diagnosed the issue. Will work on fix on monday.

**Comment by umangyadav** [comment]
this is same issue as this one #3306

**Comment by causten** [comment]
@CharlieL7  is this considered done then?
