### ISSUE TITLE
Uncomment - bugprone-empty-catch

### ISSUE THREAD

**Issue by TedThemistokleous** [ROCm/AMDMIGraphX#3470]
Investigate and cleanup tidy errors that arose via #3340 with bugprone-empty-catch

- [ ] Uncomment this in CmakeLists.txt 
- [ ] determine if false positive or requires fix
- [ ] Fix code causing the failure

**Comment by taylding-amd** [comment]
After disabling the -bugprone-empty-catch flag, I found that clang tidy only reported an error in test.hpp. The error was a false positive, and no fix is required.
![image](https://github.com/user-attachments/assets/b9048cdb-c2fa-4623-847c-449ddcb4fa0b)

**Comment by TedThemistokleous** [comment]
Seems like a false positive.
