### ISSUE TITLE
Uncomment - -bugprone-unused-local-non-trivial-variable

### ISSUE THREAD

**Issue by TedThemistokleous** [ROCm/AMDMIGraphX#3471]
Disabled tidy check in #3340 

- [ ] Uncomment and investigate
- [ ] Fix code if able
- [ ] reneable check

**Comment by taylding-amd** [comment]
After turning off -bugprone-unused-local-non-trivial-variable, two unused local variable errors was reported:
1. src/module.cpp:1136:
![image](https://github.com/user-attachments/assets/18dca0cb-c40e-48ff-8203-ffff3c26c109)


2. program.cpp:1019
![image](https://github.com/user-attachments/assets/09fd4284-d1a1-4586-931f-07b58b7b1f9f)

**Comment by TedThemistokleous** [comment]
Pull those out, rebuild, run a make -j$(nproc) check and then ensure that doesn't break anything. I don't think it would break anything if you removed this. Open PR after and I can approve
