### ISSUE TITLE
Uncomment -bugprone-multi-level-implicit-pointer-conversion

### ISSUE THREAD

**Issue by TedThemistokleous** [ROCm/AMDMIGraphX#3472]
Needed to be commented out by #3340

- [ ] Uncomment and investigate
- [ ] Fix code that causes this if able
- [ ] determine if test stops false positive or worth having on

**Comment by taylding-amd** [comment]
Two tidy check errors:

![Screenshot 2024-11-12 213908](https://github.com/user-attachments/assets/278638a2-0f86-4042-a469-91de6980f4bb)
![image](https://github.com/user-attachments/assets/55d1c917-6954-40d4-bc82-450098aff057)

![Screenshot 2024-11-12 105727](https://github.com/user-attachments/assets/f64cd39a-9b4b-4dd6-a7d1-ea63a72e7682)
![image](https://github.com/user-attachments/assets/04c9e240-a684-40c5-83ee-090ae700c870)
