### ISSUE TITLE
unregistered operation 'migraphx.max' found in dialect ('migraphx')

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/AMDMIGraphX#3479]
MLIR attention does not seem to support the pointwise max operation, need to add check for it in the fuse_mlir pass.

Adjacent problem to #3439. Occurs when compiling the same model using mlir attention.

**Comment by pfultz2** [comment]
We probably need to add this operator to mlir, but it still is probably good to check for supported pointwise before fusing attention.

**Comment by shivadbhavsar** [comment]
Agreed, is that a change in migraphx or is that something mlir needs to support first?

**Comment by pfultz2** [comment]
Its a change that needs to happen in mlir, but it should be simple to add.
