### ISSUE TITLE
[Issue]: How to Enable Multi-GPUs for Data Parallel

### ISSUE THREAD

**Issue by zixianwang2022** [ROCm/AMDMIGraphX#3557]
### Problem Description

Hi, 

I am looking into the MIGraphX documentation, but I didn't find where I can specify device_id for my mgx model. Is there a way to do this through the MIGraphX Python API? 

### Operating System

Rocky Linux

### CPU

EPYC 7V13 64 Core

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 6.0.0

**Comment by pfultz2** [comment]
You need to call [`hipSetDevice`](https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/doxygen/html/group___device.html#ga43c1e7f15925eeb762195ccb5e063eae) before compiling or loading to have the model run on that device.

**Comment by zixianwang2022** [comment]
> You need to call [`hipSetDevice`](https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/doxygen/html/group___device.html#ga43c1e7f15925eeb762195ccb5e063eae) before compiling or loading to have the model run on that device.

It works. Thank you!
