### ISSUE TITLE
Support ONNX file with different IR version

### ISSUE THREAD

**Issue by scxiao** [ROCm/AMDMIGraphX#383]
Current AMDMIGraphX implementation mainly focus on support onnx with the IR 0.0.4. As we get real external users, their models may be exported with the ONNX IR version 0.0.3, which will break on our current implementation. 

We may need additional work to support ONNX models with older ONNX IR version. 

Note that, tensorrt supports the onnx IR version 0.0.3

**Comment by mvermeulen** [comment]
Note: ONNX 1.6 was just released: https://github.com/onnx/onnx/releases

The set of versions in the github.com/onnx/onnx/onnx.proto3 definition now are up to 6 which I assume is 0.0.6 (?)

**Comment by scxiao** [comment]
yes, the IR version in 1.6 is 0.0.6 as in: https://github.com/onnx/onnx/blob/master/docs/Versioning.md

**Comment by causten** [comment]
Done
