### ISSUE TITLE
Various issues identified from onnx backend tests

### ISSUE THREAD

**Issue by scxiao** [ROCm/AMDMIGraphX#582]
After running all the tests, the following issues are identified:

1. possible race condition (all outputs are 0)
test_Conv1d_dilated_cpu
test_shape_example_cpu
test_shape_cpu
test_constant_cpu

2. bugs in rewrite pooling (output shape is modified, issue #575 is created)
test_AvgPool1d_stride_cpu
test_AvgPool1d_cpu

3. different softmax/logsoftmax implementation (know issue)
test_softmax_default_axis_cpu
test_softmax_axis_1_cpu
test_softmax_axis_0_cpu
test_logsoftmax_default_axis_cpu
test_logsoftmax_axis_1_cpu
test_logsoftmax_axis_0_cpu

4. no support for column major format and 2 outputs (known issue, need support from MIOpen)
test_maxpool_with_argmax_2d_precomputed_strides_cpu
test_maxpool_with_argmax_2d_precomputed_pads_cpu

5. no support for dilations in maxpool (know issue, need support from MIOpen)
test_maxpool_2d_dilations_cpu

6. lrn unknow error, GPU results are wrong, CPU results are correct
test_lrn_default_cpu
test_lrn_cpu

7. eliminate_concat problem (issue #573 is created)
test_concat_3d_axis_negative_1_cpu
test_concat_2d_axis_negative_1_cpu
test_concat_3d_axis_negative_2_cpu

8 Dynamic shape is not supported (known issue)
test_expand_shape_model4_cpu
test_expand_shape_model3_cpu
test_expand_shape_model2_cpu
test_expand_shape_model3_cpu

9. Int64 data type is not supported (issue #581 is created)
test_operator_non_float_params_cpu
test_Embedding_sparse_cpu
test_gather_negative_indices_cpu

10 MULTIBROADCAST does not support scalar inputs (issue #580 is created)
test_clip_default_max_cpu
test_clip_default_inbounds_cpu

**Comment by scxiao** [comment]
Issues in item 8 is resolved.

**Comment by scxiao** [comment]
Issues in item 10 is resolved.

**Comment by causten** [comment]
fixed
