### ISSUE TITLE
Int8 is slower than FP32 and FP16

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#682]
Recently I have been testing MIGraphX inference. I find than int8 is slower than FP32 and FP16(such as VGG16,Resnet50). I do not know why?

**Comment by pfultz2** [comment]
This is expected right now. Work still needs to be done to optimize and tune our libraries for int8. We plan to work on that in the future.

**Comment by causten** [comment]
ROCm 6.0 has fixed this.

**Comment by HeeebsInc** [comment]
I am seeing this behavior in ROCm 6.4.  FP16 I am seeing 102 FPS, and Int8 I am seeing 4 FPS. I am running on a 7600 XT

Any advice on how to accomplish this? @causten 

My network is predominantly convolutions with SiLU activations, in `nchw` format
