### ISSUE TITLE
Full dynamic shape support

### ISSUE THREAD

**Issue by scxiao** [ROCm/AMDMIGraphX#689]
We have more and more scenarios in which dynamic shape support is needed. Some examples include:
1) MLperf test dynamic sequence lengths and batch size for the BERT model.
2) Dynamic output shape of ONNX operators such as If, Resize, Padding, Slice...

Currently, we limit the inputs we can support, so only fixed shapes need to be processed in the scenarios mentioned above. In the long term, we need to come up with a solution to support dynamic shapes.

One possible approach is: when compiling a program, we can limit the max dims we can support, and the max dims is compatible with smaller dims and not doing unnecessary computation.

**Comment by scxiao** [comment]
After investigating the tensorrt, it provides the following solution to the If and Loop:
1) the if operator condition must be constant or can be inferred as an constant.
    Non-constant cond input of If operator has the following error msg:
Assertion failed: cond.is_weights() && cond.weights().count() == 1 && "If condition must be a initializer!"
ERROR: could not parse the model.

2) Loop operator must limit the max iterations according to the API specification as in https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_loop.html#addc1dd8e1453b9154fe734d96b05c274 
The possible reason is to be able to handle the concatenation of outputs of each iteration.

The two onnx files I tried are attached here.
[onnx.zip](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/5613648/onnx.zip)

**Comment by nartmada** [comment]
Hi @scxiao, I am cleaning up old tickets here.  Has this task been completed?  Thanks.

**Comment by CharlieL7** [comment]
Dynamic shapes are not fully done (more operators, GPU support), but at a stage where we can close this issue for now.
