### ISSUE TITLE
FCN-Resnet, "PARSE_RESIZE: only nearest mode is supported!"

### ISSUE THREAD

**Issue by cagery** [ROCm/AMDMIGraphX#725]
When parsed with MIGraphX, two FCN-Resnet models error out with:
```
MIGraphX Error: /cgMIGraphX/AMDMIGraphX/src/onnx/parse_resize.cpp:100: parse: PARSE_RESIZE: only nearest mode is supported!
```

- /models/vision/object_detection_segmentation/fcn/model/fcn-resnet50-11.onnx   
- /models/vision/object_detection_segmentation/fcn/model/fcn-resnet101-11.onnx

**Comment by kahmed10** [comment]
This model uses "linear" interpolation mode.

**Comment by scxiao** [comment]
#819 can fix this issue. Works well using Rocm4.2. In rocm4.1, there is an error related to miopen as:

```
terminate called after throwing an instance of 'miopen::Exception'
  what():  /root/driver/MLOpen/src/tmp_dir.cpp:45: Can't execute cd /tmp/miopen-MIOpenConv1x1J1.cl-b9b7-9070-f7d2-f448; /opt/rocm-4.1.0/bin/clang-ocl  -DMLO_FILTER_STRIDE0=1 -DMLO_FILTER_STRIDE1=1 -DMLO_N_LCL_IN_MAPS_ONCE=8 -DBATCHSIZE=1 -DH=1 -DW=1 -DC=384 -DK=512 -DMLO_N_LCL_IN_MAPS=128 -DMLO_N_INPUTS=384 -DMLO_N_OUTPUTS=512 -DH_out=1 -DW_out=1 -DMLO_N_IN_GROUPS=3 -DMLO_CLOOP0=16 -DMLO_CLOOP2=16 -DMLO_N_LCL_OUT_MAPS=32 -DMLO_CHEAT_SHADER_COMPILER=0 -DMLopen_RUNNING=1 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=0 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -mcpu=gfx906 -Wno-everything -mcode-object-version=4 MIOpenConv1x1J1.cl -o /tmp/miopen-MIOpenConv1x1J1.cl-b9b7-9070-f7d2-f448/MIOpenConv1x1J1.cl.o
Aborted (core dumped)
```

**Comment by cagery** [comment]
Re-confirmed @scxiao 's observation on 4.2. There is no parsing issue anymore; but `migrahx-driver verify` with GPU is failing to match. Investigating.

**Comment by cagery** [comment]
The following convolution is causing a mismatch in this model. (Found via reduction using migraphx-driver).
Will debug further and update.

```
main:@264 = convolution[padding={2, 2, 2, 2},stride={1, 1},dilation={2, 2},group=1,padding_mode=0](main:@263,main:@81) -> float_type, {1, 256, 1, 1}, {256, 1, 1, 1}

Input from 263 --->.  main:@263 = relu(main:@262) -> float_type, {1, 256, 1, 1}, {256, 1, 1, 1}

Input from 81:   ---> main:@81 = @literal{ ... } -> float_type, {256, 256, 3, 3}, {2304, 9, 3, 1}
```

**Comment by cagery** [comment]
Debugged this further. From comparison to other not-failing convolutions in this model, the failing one has dilation of {2,2}. I have created an isolated test case for verify, and I can reproduce the failure by changing dilation between {1,1} and {2,2}. Looked into MIOpen logs, seems like correct values are passed. Filed an issue with MIOpen team to get them look at what might be going wrong.
