### ISSUE TITLE
FP16 is much slower than FP32

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/AMDMIGraphX#763]
When I use migraphx to do inference on Rocm,I find that FP16 is much slower than FP32 on VGG network when batchsize is set to 1. I try to do profiling and find that the function rocblas_gemm_ex is the reason. But I do not know why.

**Comment by qianqing13579** [comment]
I set ROCBLAS_LAYER=3 on VGG network with batchsize=1, and I see a lot of information as follows.
FP32:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7fadbf200000,f32_r,4096,0x7fb655204000,f32_r,25088,1,0x7fb655266000,f32_r,4096,0x7fb655266000,f32_r,4096,f32_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f32_r --lda 4096 --b_type f32_r --ldb 25088 --beta 1 --c_type f32_r --ldc 4096 --d_type f32_r --ldd 4096 --compute_type f32_r --algo 0 --solution_index 0 --flags 0

FP16:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7f40aa600000,f16_r,4096,0x7f40a0a047d0,f16_r,25088,1,0x7f40a0a027d0,f16_r,4096,0x7f40a0a027d0,f16_r,4096,f16_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f16_r --lda 4096 --b_type f16_r --ldb 25088 --beta 1 --c_type f16_r --ldc 4096 --d_type f16_r --ldd 4096 --compute_type f16_r --algo 0 --solution_index 0 --flags 0

**Comment by qianqing13579** [comment]
I set ROCBLAS_LAYER=3 on VGG network with batchsize=1, and I see a lot of information as follows.
FP32:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7fadbf200000,f32_r,4096,0x7fb655204000,f32_r,25088,1,0x7fb655266000,f32_r,4096,0x7fb655266000,f32_r,4096,f32_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f32_r --lda 4096 --b_type f32_r --ldb 25088 --beta 1 --c_type f32_r --ldc 4096 --d_type f32_r --ldd 4096 --compute_type f32_r --algo 0 --solution_index 0 --flags 0

FP16:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7f40aa600000,f16_r,4096,0x7f40a0a047d0,f16_r,25088,1,0x7f40a0a027d0,f16_r,4096,0x7f40a0a027d0,f16_r,4096,f16_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f16_r --lda 4096 --b_type f16_r --ldb 25088 --beta 1 --c_type f16_r --ldc 4096 --d_type f16_r --ldd 4096 --compute_type f16_r --algo 0 --solution_index 0 --flags 0

**Comment by kahmed10** [comment]
Which GPU do you have? I have tested VGG16 batch size=1 on Radeon VII, and although it is not a significant speedup (which is a known issue with MIOpen fp16 support), I am not seeing a regression.

Also, if there is a specific model that you want me to test, feel free to share.

**Comment by qianqing13579** [comment]
@kahmed10 
I use rocm3.3. I use rocminfo command,and the output is as follows:
  Name:                    gfx906                             
  Marketing Name:          Vega 20                            
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    9                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26273(0x66a1)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1600                               
  BDFID:                   37120                              
  Internal Node ID:        9                                  
  Compute Unit:            60                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx906          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32

**Comment by kahmed10** [comment]
I am using ROCm 3.7. Can you try with the newer version and see if it fixes the issue?

Here is a prebuilt image:
`docker pull scxiao/onnxruntime_migraphx:rocm3.7`

Also, if that doesn't resolve the issue, please let me know which version of VGG you are testing so that I can try reproducing.

**Comment by zhangjia3** [comment]
@kahmed10  @pfultz2 can you install OpenCV-python in image of scxiao/onnxruntime_migraphx:rocm3.7？

**Comment by scxiao** [comment]
Can you try "sudo apt update && sudo apt-get install python3-opencv"?

**Comment by scxiao** [comment]
If you cannot install, I will update the image with python-opencv installed.
