### ISSUE TITLE
Support multiple versions of onnx unit tests

### ISSUE THREAD

**Issue by scxiao** [ROCm/AMDMIGraphX#801]
ONNX specifications are updated with each new version of ONNX introduced, which can cause conflicts for the onnx unit tests in migraphx. In other words, the ONNX unit tests created in a previous version may become incorrect in later ONNX versions when we generate the onnx file. We need a systematic way to support multiple ONNX versions simultaneously and correctly. 

One proposal is creating a new script file for each new version of ONNX. For example, we can have a script gen_onnx_1.8.1.py for the new onnx unit tests added for the ONNX 1.8.1, then we know all the ONNX models created in this file are for ONNX 1.8.1. For the .cpp test cases, it should work for all ONNX versions, and there are no regression when we update migraphx to support new versions of ONNX.

**Comment by causten** [comment]
Will not work on.
