### ISSUE TITLE
fp16 overflow

### ISSUE THREAD

**Issue by scxiao** [ROCm/AMDMIGraphX#850]
When we do reduce_sum/mean, matrix multiplication and convolution, it is possible the accumulation of multiple elements causes an overflow. We need a solution to resolve this issues.

**Comment by scxiao** [comment]
This issue is related to issue #831

**Comment by scxiao** [comment]
For the nan outputs in the opset7(8)/fp16_inception_v1 model, they are caused by the LRN operator. If I convert fp16 to fp32 for the inputs of LRN, then convert its outputs back to fp32 in parsing the LRN operator, all outputs are correct.

**Comment by causten** [comment]
Check if we divide first for reduce mean for floats (and opposite for ints).

**Comment by nartmada** [comment]
Hi @scxiao and @causten, is this issue still opened?  I am cleaning up old tickets in ROCm/AMDMIGraphX repo.  Thanks.

**Comment by zichguan-amd** [comment]
Issue no longer exist
